import { setupWorker } from 'msw/browser'
import { handlers } from '@/mocks/handlers'

/**
 * MSW Service Worker for browser (development).
 * Started in main.tsx when VITE_USE_MOCK_API=true.
 * The service worker file (public/mockServiceWorker.js) is
 * generated by `msw init public/` (runs in postinstall).
 */
export const worker = setupWorker(...handlers)
